
columns_cleaned = {
    "grad_abs_mean": "Gradient Absolute Mean",
    "grad_mean": "Gradient Mean",
    "grad_min": "Gradient Minimum",
    "grad_max": "Gradient Maximum",
    "grad_median": "Gradient Median",
    "grad_std": "Gradient Standard Deviation",
    "grad_dir": "Gradient Direction",
    "grad_cos_dist": "Gradient Cosine Distance",
    "grad_noise_scale": "Gradient Noise Scale",
    "var_train_loss": "Variations of Training Loss",
    "accuracy_train": "Training Accuracy",
    "confidence_train": "Training Confidence",
    "accuracy_val": "Validation Accuracy",
    "confidence_val": "Validation Confidence",
    "f1_train": "Training F1 Score",
    "f1_val": "Validation F1 Score",
    "recall_train": "Training Recall",
    "recall_val": "Validation Recall",
    "precision_train": "Training Precision",
    "precision_val": "Validation Precision",
    "perplexity_train": "Training Perplexity",
    "perplexity_val": "Validation Perplexity",
    "train_loss": "Training Loss",
    "val_loss": "Validation Loss",
    "var_val_loss": "Variations of Validation Loss",
    "epoch": "Epoch",
    "accuracy": "Accuracy",
    "confidence": "Confidence",
    "f1": "F1 Score",
    "recall": "Recall",
    "precision": "Precision",
    "perplexity": "Perplexity",
    "ece": "Expected Calibration Error"
}
models_cleaned = {
    "original_transformer": "From scratch BPE",
    "original_transformer.glove": "From scratch GloVe",
    "Llama-3.2-3B": "Llama-3.2 3B",
    "Llama-3.2-3B-2": "Llama-3.2 3B",
    "Llama-3.2-3B-Instruct2": "Llama-3.2 3B Instruct",
    "Llama-3.2-1B": "Llama-3.2 1B",
    "Llama-3.2-1B-Instruct": "Llama-3.2 1B Instruct",
}