model:
  name: "DeepSeek-R1-Distill-Qwen-1.5B"
  base_model: "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
  type: "hgface"
  tokenizer: "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
  ckpt_dir: "CKPT_DIR"
  dir: "MODEL_DIR"
  config:
    max_seq_len: 2048
  lora:
    r: 4
    lora_alpha: 32
    target_modules:
      - "q_proj"
      - "k_proj"
      - "v_proj"
      - "o_proj"
    lora_dropout: 0.1
    bias: "none"
    lora_dropout: 0.1
    modules_to_save:
      - "classifier"
    
training:
  batch_size: 2
  test_batch_size: 16
  epochs: 3000
  learning_rate: 5e-5
  step_size: 20
  gamma: 0.7
  patience: 3000
  min_delta: 0.0
  weight_decay: 1e-4
  betas: [0.9, 0.999]
  optimizer: "adamw"
  loss_function: "cross_entropy"

data:
  short_answer: True
  easy_task: True
  hint: True
  max_a_length: 16

lctm:
  uq_path: "CSV_PATH"
