model:
  name: "easy-glove"
  type: "torch"
  tokenizer: "glove.6B.300d"
  config:
    # num_layers: 12
    # model_size: 512
    # dim_ffn: 1024
    # nhead: 16
    num_layers: 6
    model_size: 512
    dim_ffn: 1024
    nhead: 8
    dropout: 0.3
    max_seq_len: 1024
  ckpt_dir: "CKPT_DIR"
  dir: "MODEL_DIR"

training:
  batch_size: 4
  test_batch_size: 16
  epochs: 3000
  learning_rate: 1e-4
  step_size: 20
  gamma: 0.7
  patience: 3000
  min_delta: 0.0
  weight_decay: 0.01
  betas: [0.9, 0.999]
  optimizer: "adamw"
  loss_function: "cross_entropy"
  # type: "normal" # or "iter"

data:
  short_answer: True
  easy_task: True
  hint: True
  max_a_length: 8

lctm:
  uq_path: "CSV_PATH"
